#!/usr/bin/perl -w

my $hss=$ARGV[0];
my $cradle=$ARGV[1];
my $log="/tmp/perfecto_frame_drops.log";
my $line;
my $drops;
my $date;

open(LOG,">>$log");
my @lines = `curl http://$hss/$cradle/camera/status`;
foreach $line (@lines) {
	if ($line =~ m/<drop>(\d+)/g) {
		$drops=$1;
		chomp $drops;
		$date=get_formatted_date();
		#print "$date,$hss,$cradle,$drops\n";
		#print LOG "$date,$host,$temperature\n";
	}
}
close LOG;
if ($drops == 0 ) { print "Drops OK: $drops\n"; exit 0 }
if ($drops != 0) { print "Drops: $drops\n"; exit 2 }
print "Unknown\n";
exit 3;

sub get_formatted_date {
        my ($sec,$min,$hour,$mday,$mon,$year) = localtime(time);
        my $month = ($mon + 1);
        $year += 1900;
        #my $date = sprintf("%4d%02d%02d_%02d%02d%02d",$year,$month,$mday,$hour,$min,$sec);
        my $date = sprintf("%4d-%02d-%02d %02d:%02d:%02d",$year,$month,$mday,$hour,$min,$sec);
        return $date;
        }
